[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.install]
cmds = ['cd ProjectManager.Api && dotnet restore']

[phases.build]
cmds = ['cd ProjectManager.Api && dotnet publish -c Release -o out']

[start]
cmd = 'cd ProjectManager.Api/out && dotnet ProjectManager.Api.dll'
